### ISSUE TITLE
Twist it feedback

### ISSUE THREAD

**Issue by dHutchings** [pioneers/PiElectrical#37]
Feedback on Rev 9B before ship.

1) Silkscreen for the screw terminals could use some changes.  The silkscreen labels should still be visible even after the terminals are soldered in place, so users can look @ the board to determine which terminal is which.

2) Schematic needs net labels to the right of the R1 thru R3

3) Just a question about the motor driver.  (Confirm: is [this the link](https://www.aliexpress.com/item/Free-Shipping-30A-Mini-VNH2SP30-Stepper-Motor-Driver-Monster-Moto-Shield-module-For-Arduino/32247122784.html?ws_ab_test=searchweb0_0,searchweb201602_2,searchweb201603_1&btsid=da69fb98-fc00-470f-801d-594a49b774ae) to the motor driver?)

How is this thing mounted to the twistit?  It looks like they're both back-to-back.  Have we talked to enclosures about this?  Having the andresons going out the back will make for a very... interesting... enclosure. 

Although, tbh, i can't immediately think of a better way to do it.

**Comment by onibrow** [comment]
Cool, fixed everything. The mounting has been thought about with Aravind, its the best we can get. Thanks again Doug!
