### ISSUE TITLE
Twist it fixes for yogibear

### ISSUE THREAD

**Issue by dHutchings** [pioneers/PiElectrical#63]
Running list of fixes for yogibear for next year:

Enable falls from 4.65 (VCC) to 4.5 V when entering an error state.  The amount the voltage falls is set by a resistive network on the motor driver chip, i.e. something that we can't change.  However, this change in voltage is readable from an ADC:
- [x] Connect the "EN" pin to an ADC - capable Arduino Pro Micro pin.

**Comment by dHutchings** [comment]
- [x] Change the pull-up value for the encoders to 1k.

**Comment by dHutchings** [comment]
- [x] Add the pull-ups for the encoders back.  Value should be as stated above.
- [x] The form factor for the yogibear's red board leaves something to be desired.  Unique board-to-board connection strategies (AKA two right-angle .1" headers) may allow a flatter package.

**Comment by dHutchings** [comment]
- [ ] Add the pull-ups for the encoders back.  Value should be as stated above.
- [ ] The form factor for the yogibear's red board leaves something to be desired.  Unique board-to-board connection strategies (AKA two right-angle .1" headers) may allow a flatter package.

**Comment by onibrow** [comment]
Slide over the red board connector so the andersons can be soldered in straight up
