### ISSUE TITLE
Pull-up Network on TwistIt is screwing with the line followers

### ISSUE THREAD

**Issue by onibrow** [pioneers/PiElectrical#76]
Make the pull up network before the resistors, aka a 2x3 resistor network. 

![pic](http://i.imgur.com/5VFsk2G.jpg)

Move the box on right to before the resistor.

**Comment by onibrow** [comment]
This would entail making a 2x3 jumper part, sourcing it, and replacing it on the twistit board.

**Comment by dHutchings** [comment]
The pull-ups aren't needed at all for the line followers.

AKA: If we correctly produced the Twist-its (If we knew when to DNP the resistors), we would not have had pull-up problems..

**Comment by onibrow** [comment]
I think this is slightly wrong. We weren't using the pull ups for the line followers, as they were powered and produced their own value. The issue comes because the pull up network is interfacing at a node that **all three** read pins are semi connected to. The readings become poor when one of the sensors reads a high, causing a pull up to the other readings as their is no drain, effectively pulling up the entire network. The fix would be have the jumper connect the three terminals to the five volts, not have the a collection of the  terminals connect to the 5V which was the solution this year.

**Comment by dHutchings** [comment]
Or, we can DNP R1, R2, and R3.  That will fix the problem with the line followers (and was how we fixed it last year)

The original intent was that R1...3 would either be populated or not, depending on the needs of the specific sensor attached to the board.  This was not followed in production, and the original cause of the line follower's response tracking each other.

![screenshot from 2017-06-10 15 52 03](https://user-images.githubusercontent.com/2158534/27006865-33a9fd62-4df5-11e7-9de4-1ab282bb85f0.png)

It is true that what you are suggesting will allow a single board (twistit) to be made in a single way (always put resistors on) and allow for reconfigurability after the fact.

If that's what you're looking for, go for it!

**Comment by onibrow** [comment]
Ooooh i see thanks for that, I like that solution better.
