### ISSUE TITLE
Make TwistIt smaller

### ISSUE THREAD

**Issue by avekan33** [pioneers/PiElectrical#81]
This is probably included in some of Doug's issues, but I wanted to emphasize its position in the queue/stack. This is to enable andersons to go vertical on both sides.

**Comment by dHutchings** [comment]
Actually I think I forgot to write this down on github, so TY for remembering!

IRRC, just sliding the connector over a bit would allow for both andersons to go vertical, but there may be something better out ther.

Also, this is actually brings up one other tweak:
- [ ] Ensure that the Encoder connectors are on the same side of the Yogibear as the Motor's output cable.  (It currently isn't, thus forcing wires to do crazy things)
